version: '3'

services:
  flask_app:
    build: ./flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/app
    environment:
      - FLASK_DEBUG=1
    restart: unless-stopped

  django_app:
    build: ./django_app
    ports:
      - "8000:8000"
    volumes:
      - ./django_app:/app
    environment:
      - DEBUG=1
    restart: unless-stopped